name: Build DEB
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Checkout dist
        uses: actions/checkout@v3
        with:
          path: dist

      - name: Prepare environment
        run: sudo apt-get -y install rpm yum-utils alien gnupg

      - name: Import repos
        run: |
          sudo rpm -Uvh --nodeps http://repo.appnode.com/stable/el/7/x86_64/appnode-release-1.1-1.el7.noarch.rpm
          sudo rpm -Uvh --nodeps http://dl.appnode.com/stable/centos/7/agent/x86_64/appnode-agent-release-1.2-1.el7.x86_64.rpm
          sudo rpm -Uvh --nodeps http://dl.appnode.com/stable/centos/7/agent/x86_64/appnode-extras-release-1.1-1.el7.noarch.rpm
          sudo rpm -Uvh --nodeps http://dl.appnode.com/stable/centos/7/ccenter/x86_64/appnode-ccenter-release-1.2-1.el7.x86_64.rpm
          sudo gpg --import /etc/pki/rpm-gpg/RPM-GPG-KEY-appnode
          sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-appnode
      
      - name: Download rpms
        run: repoquery -a --location | grep appnode-  | grep -v repo. | xargs -d '\n' -n1 wget --no-verbose
        
      - name: Convert to deb
        run: sudo alien -d -c ./*.rpm
        
      - name: Move new debs to dist and commit
        run: |
          cp -rn *.deb dist/
          cd dist
          git commit -m "update"

      - name: Push dist
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
